# Generated by Django 4.2.5 on 2023-09-07 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nav_banner_created_time_banner_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nav',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='nav',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='nav',
            name='orders',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='nav',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
