# Generated by Django 4.2.5 on 2023-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wxchat',
            field=models.CharField(blank=True, default=True, max_length=64, verbose_name='微信号'),
        ),
    ]
